name: Bug / Error Report
description: Report a problem or error you experienced.
title: "[Bug]: "
labels: ["Bug / Error"]
body:
  - type: markdown
    attributes:
      value: |
        Don't forget to set a title in the box above!
  - type: checkboxes
    id: no-duplicate-issues
    validations:
      required: true
    attributes:
      label: Not a Duplicate Issue
      description: Check to make sure there are no existing open issues about your problem.
      options:
        - label: I have searched the existing issues and confirmed this is not a duplicate.
  - type: markdown
    attributes:
      value: |
        ## Type of Problem:
  - type: dropdown
    id: bug-type-early
    validations:
      required: true
    attributes:
      label: Script Stops Early or Doesn't Run  (If applicable)
      description: Select one of these if the script crashes or stops early
      options:
        - ''
        - Not applicable
        - Crashes/stops immediately BEFORE the GUI
        - Crashes almost immediately AFTER the GUI
        - Script runs for a bit then crashes / stops early
  - type: dropdown
    id: bug-type-finish
    attributes:
      label: Script Finishes But With a Problem (If applicable)
      description: Select one of these if the script finishes but doesn't do what it's supposed to.
      options:
        - ''
        - Not applicable
        - Script finishes, but fails to create any shortcuts of a certain type
        - Script finishes, but a problem occurs while searching for links
        - Script finishes, but a problem occurs in creating the actual shortcut files
        - Something Else - Script finishes but a different problem or unexpected behavior occurred
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug, such as what happened before it occurred, what happened next, any special context that causes it, etc.
      placeholder: "I got an error when... then it did this..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Script Version
      description: What version of Windows Super God Mode are you using? (It will say so at the bottom right of the GUI window.)
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps or conditions to reproduce
      description: Provide any special steps to reproduce the issue.
      placeholder: Step 1, Step 2, Step 3...
      value: |
             1. 
             2. 
             3. 
    validations:
      required: true
  - type: dropdown
    id: windows-version
    attributes:
      label: Windows Version
      description: What version of Windows are you using?
      multiple: false
      options:
        - ''
        - Windows 11
        - Windows 10
        - Windows 8.1
        - Windows 7
        - Other (please specify in the description)
    validations:
      required: true
  - type: dropdown
    id: execution-method
    attributes:
      label: How did you run the script?
      multiple: false
      options:
        - ''
        - GUI via launcher batch file
        - GUI via PowerShell terminal
        - Command Line Only (Using -NoGUI)
        - Using a debugger like VSCode
    validations:
      required: true
  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste any error messages or unexpected output here.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as specific settings used or system configuration.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can upload images by dragging and dropping them into this box.
