blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/ThioJoe/Windows-Super-God-Mode/discussions/new?category=ideas-suggestions
    about: Please create feature requests in the Discussions tab.
